FROM mcr.microsoft.com/devcontainers/base:ubuntu-24.04

RUN apt-get update \
    && apt-get install -y --no-install-recommends build-essential python3 python3-pip make \
    && rm -rf /var/lib/apt/lists/*

